package en

var Commodities = map[string]string{
	"advancedcatalysers":              "Advanced Catalysers",
	"advancedmedicines":               "Advanced Medicines",
	"advert1":                         "Ultra-Compact Processor Prototypes",
	"aerialedenapple":                 "Eden Apples Of Aerial",
	"agriculturalmedicines":           "Agri-Medicines",
	"agronomictreatment":              "Agronomic Treatment",
	"alacarakmoskinart":               "Alacarakmo Skin Art",
	"albinoquechuamammoth":            "Albino Quechua Mammoth Meat",
	"alexandrite":                     "Alexandrite",
	"algae":                           "Algae",
	"alieneggs":                       "Leathery Eggs",
	"altairianskin":                   "Altairian Skin",
	"aluminium":                       "Aluminium",
	"alyabodilysoap":                  "Alya Body Soap",
	"ancientcasket":                   "Guardian Casket",
	"ancientkey":                      "Ancient Key",
	"ancientorb":                      "Guardian Orb",
	"ancientrelic":                    "Guardian Relic",
	"ancientrelictg":                  "Unclassified Relic",
	"ancienttablet":                   "Guardian Tablet",
	"ancienttotem":                    "Guardian Totem",
	"ancienturn":                      "Guardian Urn",
	"anduligafireworks":               "Anduliga Fire Works",
	"animalmeat":                      "Animal Meat",
	"animalmonitors":                  "Animal Monitors",
	"antiquejewellery":                "Antique Jewellery",
	"anynacoffee":                     "Any Na Coffee",
	"apavietii":                       "Apa Vietii",
	"aquaponicsystems":                "Aquaponic Systems",
	"aroucaconventualsweets":          "Arouca Conventual Sweets",
	"articulationmotors":              "Articulation Motors",
	"assaultplans":                    "Assault Plans",
	"atmosphericextractors":           "Atmospheric Processors",
	"autofabricators":                 "Auto-Fabricators",
	"azcancriformula42":               "AZ Cancri Formula 42",
	"bakedgreebles":                   "Baked Greebles",
	"baltahsinevacuumkrill":           "Baltah'sine Vacuum Krill",
	"bankiamphibiousleather":          "Banki Amphibious Leather",
	"basicmedicines":                  "Basic Medicines",
	"bastsnakegin":                    "Bast Snake Gin",
	"bauxite":                         "Bauxite",
	"beer":                            "Beer",
	"belalansrayleather":              "Belalans Ray Leather",
	"benitoite":                       "Benitoite",
	"bertrandite":                     "Bertrandite",
	"beryllium":                       "Beryllium",
	"bioreducinglichen":               "Bioreducing Lichen",
	"biowaste":                        "Biowaste",
	"bismuth":                         "Bismuth",
	"bluemilk":                        "Azure Milk",
	"bootlegliquor":                   "Bootleg Liquor",
	"bromellite":                      "Bromellite",
	"buckyballbeermats":               "Buckyball Beer Mats",
	"buildingfabricators":             "Building Fabricators",
	"burnhambiledistillate":           "Burnham Bile Distillate",
	"cd75catcoffee":                   "CD-75 Kitten Brand Coffee",
	"centaurimegagin":                 "Centauri Mega Gin",
	"ceramiccomposites":               "Ceramic Composites",
	"ceremonialheiketea":              "Ceremonial Heike Tea",
	"cetiaepyornisegg":                "Aepyornis Egg",
	"cetirabbits":                     "Ceti Rabbits",
	"chameleoncloth":                  "Chameleon Cloth",
	"chateaudeaegaeon":                "Chateau De Aegaeon",
	"chemicalwaste":                   "Chemical Waste",
	"cherbonesbloodcrystals":          "Cherbones Blood Crystals",
	"chieridanimarinepaste":           "Chi Eridani Marine Paste",
	"classifiedexperimentalequipment": "Classified Experimental Equipment",
	"clothing":                        "Clothing",
	"cmmcomposite":                    "CMM Composite",
	"cobalt":                          "Cobalt",
	"coffee":                          "Coffee",
	"coltan":                          "Coltan",
	"comercialsamples":                "Commercial Samples",
	"computercomponents":              "Computer Components",
	"conductivefabrics":               "Conductive Fabrics",
	"consumertechnology":              "Consumer Technology",
	"coolinghoses":                    "Micro-weave Cooling Hoses",
	"copper":                          "Copper",
	"coquimspongiformvictuals":        "Coquim Spongiform Victuals",
	"cropharvesters":                  "Crop Harvesters",
	"cryolite":                        "Cryolite",
	"crystallinespheres":              "Crystalline Spheres",
	"damnacarapaces":                  "Damna Carapaces",
	"datacore":                        "Data Core",
	"deltaphoenicispalms":             "Delta Phoenicis Palms",
	"deuringastruffles":               "Deuringas Truffles",
	"diagnosticsensor":                "Hardware Diagnostic Sensor",
	"diplomaticbag":                   "Diplomatic Bag",
	"disomacorn":                      "Diso Ma Corn",
	"domesticappliances":              "Domestic Appliances",
	"duradrives":                      "Duradrives",
	"earthrelics":                     "Earth Relics",
	"eleuthermals":                    "Eleu Thermals",
	"emergencypowercells":             "Emergency Power Cells",
	"encripteddatastorage":            "Encrypted Data Storage",
	"encryptedcorrespondence":         "Encrypted Correspondence",
	"eraninpearlwhisky":               "Eranin Pearl Whisky",
	"eshuumbrellas":                   "Eshu Umbrellas",
	"esusekucaviar":                   "Esuseku Caviar",
	"ethgrezeteabuds":                 "Ethgreze Tea Buds",
	"evacuationshelter":               "Evacuation Shelter",
	"exhaustmanifold":                 "Exhaust Manifold",
	"explosives":                      "Explosives",
	"fish":                            "Fish",
	"foodcartridges":                  "Food Cartridges",
	"fossilremnants":                  "Fossil Remnants",
	"fruitandvegetables":              "Fruit and Vegetables",
	"fujintea":                        "Fujin Tea",
	"galactictravelguide":             "Galactic Travel Guide",
	"gallite":                         "Gallite",
	"gallium":                         "Gallium",
	"geawendancedust":                 "Geawen Dance Dust",
	"genebank":                        "Gene Bank",
	"geologicalequipment":             "Geological Equipment",
	"geologicalsamples":               "Geological Samples",
	"gerasiangueuzebeer":              "Gerasian Gueuze Beer",
	"giantirukamasnails":              "Giant Irukama Snails",
	"giantverrix":                     "Giant Verrix",
	"gold":                            "Gold",
	"gomanyauponcoffee":               "Goman Yaupon Coffee",
	"goslarite":                       "Goslarite",
	"grain":                           "Grain",
	"grandidierite":                   "Grandidierite",
	"haidneblackbrew":                 "Haiden Black Brew",
	"harmasilversearum":               "Harma Silver Sea Rum",
	"havasupaidreamcatcher":           "Havasupai Dream Catcher",
	"hazardousenvironmentsuits":       "H.E. Suits",
	"heatsinkinterlink":               "Heatsink Interlink",
	"heliostaticfurnaces":             "Microbial Furnaces",
	"helvetitjpearls":                 "Helvetitj Pearls",
	"hip10175bushmeat":                "HIP 10175 Bush Meat",
	"hip41181squid":                   "HIP Proto-Squid",
	"hiporganophosphates":             "Hip Organophosphates",
	"hnshockmount":                    "HN Shock Mount",
	"honestypills":                    "Honesty Pills",
	"hr7221wheat":                     "HR 7221 Wheat",
	"hydrogenfuel":                    "Hydrogen Fuel",
	"hydrogenperoxide":                "Hydrogen Peroxide",
	"imperialslaves":                  "Imperial Slaves",
	"indibourbon":                     "Indi Bourbon",
	"indite":                          "Indite",
	"indium":                          "Indium",
	"insulatingmembrane":              "Insulating Membrane",
	"iondistributor":                  "Ion Distributor",
	"jadeite":                         "Jadeite",
	"jaquesquinentianstill":           "Jaques Quinentian Still",
	"jaradharrepuzzlebox":             "Jaradharre Puzzle Box",
	"jarouarice":                      "Jaroua Rice",
	"jotunmookah":                     "Jotun Mookah",
	"kachiriginleaches":               "Kachirigin Filter Leeches",
	"kamitracigars":                   "Kamitra Cigars",
	"karetiicouture":                  "Karetii Couture",
	"karsukilocusts":                  "Karsuki Locusts",
	"kinagoinstruments":               "Kinago Violins",
	"konggaale":                       "Kongga Ale",
	"korrokungpellets":                "Koro Kung Pellets",
	"lanthanum":                       "Lanthanum",
	"largeexplorationdatacash":        "Large Survey Data Cache",
	"lavianbrandy":                    "Lavian Brandy",
	"leather":                         "Leather",
	"leestianeviljuice":               "Leestian Evil Juice",
	"lepidolite":                      "Lepidolite",
	"lftvoidextractcoffee":            "Void Extract Coffee",
	"liquidoxygen":                    "Liquid oxygen",
	"liquor":                          "Liquor",
	"lithium":                         "Lithium",
	"lithiumhydroxide":                "Lithium Hydroxide",
	"livehecateseaworms":              "Live Hecate Sea Worms",
	"lowtemperaturediamond":           "Low Temp. Diamonds",
	"ltthypersweet":                   "LTT Hyper Sweet",
	"m_tissuesample_fluid":            "Mollusc Fluid",
	"m_tissuesample_nerves":           "Mollusc Brain Tissue",
	"m_tissuesample_soft":             "Mollusc Soft Tissue",
	"m3_tissuesample_membrane":        "Mollusc Membrane",
	"m3_tissuesample_mycelium":        "Mollusc Mycelium",
	"m3_tissuesample_spores":          "Mollusc Spores",
	"magneticemittercoil":             "Magnetic Emitter Coil",
	"marinesupplies":                  "Marine Equipment",
	"mechucoshightea":                 "Mechucos High Tea",
	"medbstarlube":                    "Medb Starlube",
	"medicaldiagnosticequipment":      "Medical Diagnostic Equipment",
	"metaalloys":                      "Meta-Alloys",
	"methaneclathrate":                "Methane Clathrate",
	"methanolmonohydratecrystals":     "Methanol Monohydrate Crystals",
	"microcontrollers":                "Micro Controllers",
	"militarygradefabrics":            "Military Grade Fabrics",
	"mineralextractors":               "Mineral Extractors",
	"mineraloil":                      "Mineral Oil",
	"modularterminals":                "Modular Terminals",
	"moissanite":                      "Moissanite",
	"mokojingbeastfeast":              "Mokojing Beast Feast",
	"momusbogspaniel":                 "Momus Bog Spaniel",
	"monazite":                        "Monazite",
	"mukusubiichitinos":               "Mukusubii Chitin-os",
	"mulachigiantfungus":              "Mulachi Giant Fungus",
	"musgravite":                      "Musgravite",
	"mutomimager":                     "Muon Imager",
	"mysteriousidol":                  "Mysterious Idol",
	"nanobreakers":                    "Nanobreakers",
	"nanomedicines":                   "Nanomedicines",
	"naturalfabrics":                  "Natural Fabrics",
	"neofabricinsulation":             "Neofabric Insulation",
	"neritusberries":                  "Neritus Berries",
	"nerveagents":                     "Nerve Agents",
	"ngadandarifireopals":             "Ngadandari Fire Opals",
	"ngunamodernantiques":             "Nguna Modern Antiques",
	"njangarisaddles":                 "Njangari Saddles",
	"noneuclidianexotanks":            "Non Euclidian Exotanks",
	"nonlethalweapons":                "Non-Lethal Weapons",
	"ochoengchillies":                 "Ochoeng Chillies",
	"onionheadc":                      "Onionhead Gamma Strain",
	"opal":                            "Void Opal",
	"ophiuchiexinoartefacts":          "Ophiuch Exino Artefacts",
	"orrerianviciousbrew":             "Orrerian Vicious Brew",
	"osmium":                          "Osmium",
	"p_particulatesample":             "Anomaly Particles",
	"painite":                         "Painite",
	"palladium":                       "Palladium",
	"pantaaprayersticks":              "Pantaa Prayer Sticks",
	"pavoniseargrubs":                 "Pavonis Ear Grubs",
	"performanceenhancers":            "Performance Enhancers",
	"personalgifts":                   "Festive Gifts",
	"pesticides":                      "Pesticides",
	"platinum":                        "Platinum",
	"platinumaloy":                    "Platinum Alloy",
	"polymers":                        "Polymers",
	"powerconverter":                  "Power Converter",
	"powergenerators":                 "Power Generators",
	"powergridassembly":               "Energy Grid Assembly",
	"powertransferconduits":           "Power Transfer Bus",
	"praseodymium":                    "Praseodymium",
	"preciousgems":                    "Precious Gems",
	"progenitorcells":                 "Progenitor Cells",
	"pyrophyllite":                    "Pyrophyllite",
	"radiationbaffle":                 "Radiation Baffle",
	"rajukrustoves":                   "Rajukru Multi-Stoves",
	"rapabaosnakeskins":               "Rapa Bao Snake Skins",
	"reactivearmour":                  "Reactive Armour",
	"reinforcedmountingplate":         "Reinforced Mounting Plate",
	"resonatingseparators":            "Resonating Separators",
	"rhodplumsite":                    "Rhodplumsite",
	"robotics":                        "Robotics",
	"rockforthfertiliser":             "Rockforth Fertiliser",
	"rusanioldsmokey":                 "Rusani Old Smokey",
	"rutile":                          "Rutile",
	"s_tissuesample_cells":            "Pod Core Tissue",
	"s_tissuesample_core":             "Pod Surface Tissue",
	"s_tissuesample_surface":          "Pod Dead Tissue",
	"s6_tissuesample_cells":           "Pod Outer Tissue",
	"s6_tissuesample_coenosarc":       "Pod Shell Tissue",
	"s6_tissuesample_mesoglea":        "Pod Mesoglea",
	"s9_tissuesample_shell":           "Pod Tissue",
	"samarium":                        "Samarium",
	"sanumameat":                      "Sanuma Decorative Meat",
	"sap8corecontainer":               "SAP 8 Core Container",
	"saxonwine":                       "Saxon Wine",
	"scientificresearch":              "Scientific Research",
	"scientificsamples":               "Scientific Samples",
	"scrap":                           "Scrap",
	"semiconductors":                  "Semiconductors",
	"serendibite":                     "Serendibite",
	"shanscharisorchid":               "Shan's Charis Orchid",
	"silver":                          "Silver",
	"skimercomponents":                "Skimmer Components",
	"smallexplorationdatacash":        "Small Survey Data Cache",
	"soontillrelics":                  "Soontill Relics",
	"sothiscrystallinegold":           "Sothis Crystalline Gold",
	"spacepioneerrelics":              "Space Pioneer Relics",
	"structuralregulators":            "Structural Regulators",
	"superconductors":                 "Superconductors",
	"surfacestabilisers":              "Surface Stabilisers",
	"survivalequipment":               "Survival Equipment",
	"syntheticfabrics":                "Synthetic Fabrics",
	"syntheticmeat":                   "Synthetic Meat",
	"syntheticreagents":               "Synthetic Reagents",
	"taaffeite":                       "Taaffeite",
	"tacticaldata":                    "Tactical Data",
	"tanmarktranquiltea":              "Tanmark Tranquil Tea",
	"tantalum":                        "Tantalum",
	"taurichimes":                     "Tauri Chimes",
	"tea":                             "Tea",
	"telemetrysuite":                  "Telemetry Suite",
	"terrainenrichmentsystems":        "Land Enrichment Systems",
	"thallium":                        "Thallium",
	"thargoidgeneratortissuesample":   "Caustic Tissue Sample",
	"thargoidheart":                   "Thargoid Heart",
	"thargoidscouttissuesample":       "Thargoid Scout Tissue Sample",
	"thargoidtissuesampletype1":       "Thargoid Cyclops Tissue Sample",
	"thargoidtissuesampletype2":       "Thargoid Basilisk Tissue Sample",
	"thargoidtissuesampletype3":       "Thargoid Medusa Tissue Sample",
	"thargoidtissuesampletype4":       "Thargoid Hydra Tissue Sample",
	"thargoidtissuesampletype5":       "Thargoid Orthrus Tissue Sample",
	"thehuttonmug":                    "The Hutton Mug",
	"thermalcoolingunits":             "Thermal Cooling Units",
	"thorium":                         "Thorium",
	"thrutiscream":                    "Thrutis Cream",
	"tiegfriessynthsilk":              "Tiegfries Synth Silk",
	"timecapsule":                     "Time Capsule",
	"tiolcewaste2pasteunits":          "Tiolce Waste2Paste Units",
	"titanium":                        "Titanium",
	"tobacco":                         "Tobacco",
	"toxandjivirocide":                "Toxandji Virocide",
	"transgeniconionhead":             "Lucan Onionhead",
	"tritium":                         "Tritium",
	"unknownartifact":                 "Thargoid Sensor",
	"unknownartifact2":                "Thargoid Probe",
	"unknownartifact3":                "Thargoid Link",
	"unknownbiologicalmatter":         "Thargoid Biological Matter",
	"unknownresin":                    "Thargoid Resin",
	"unknowntechnologysamples":        "Thargoid Technology Samples",
	"unocuppiedescapepod":             "Unoccupied Escape Pod",
	"unstabledatacore":                "Unstable Data Core",
	"uraninite":                       "Uraninite",
	"uranium":                         "Uranium",
	"usscargorareartwork":             "Rare Artwork",
	"uszaiantreegrub":                 "Uszaian Tree Grub",
	"utgaroarmillenialeggs":           "Utgaroar Millennial Eggs",
	"uzumokulowgwings":                "Uzumoku Low-G Wings",
	"vanayequirhinofur":               "Vanayequi Ceratomorpha Fur",
	"vegaslimweed":                    "Vega Slimweed",
	"vherculisbodyrub":                "V Herculis Body Rub",
	"vidavantianlace":                 "Vidavantian Lace",
	"volkhabbeedrones":                "Volkhab Bee Drones",
	"water":                           "Water",
	"waterpurifiers":                  "Water Purifiers",
	"watersofshintara":                "The Waters Of Shintara",
	"wheemetewheatcakes":              "Wheemete Wheat Cakes",
	"wine":                            "Wine",
	"witchhaulkobebeef":               "Witchhaul Kobe Beef",
	"wulpahyperboresystems":           "Wulpa Hyperbore Systems",
	"wuthielokufroth":                 "Wuthielo Ku Froth",
	"xihecompanions":                  "Xihe Biomorphic Companions",
	"yasokondileaf":                   "Yaso Kondi Leaf",
	"zeesszeantglue":                  "Zeessze Ant Grub Glue",
}
